services:
  db:
    image: johnson94/fasms-docker-db
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd_2024
      MYSQL_DATABASE: fasms_dev
    ports:
      - "3306:3306"

  phpmyadmin:
    image: johnson94/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: P@ssw0rd_2024
    depends_on:
      db:
        condition: service_healthy

  web:
    image: johnson94/fasms-docker-web
    container_name: web
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: P@ssw0rd_2024
      DB_NAME: fasms_dev
      JWT_SECRET: myStrongJwtSecretKey123!@#
    depends_on:
      db:
        condition: service_healthy