services:
  # Node.js Backend Service
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: P@ssw0rd_2024
      DB_NAME: fasms_dev
      JWT_SECRET: myStrongJwtSecretKey123!@#
    volumes:
      - .:/usr/src/app  # This maps your local code to the container
    depends_on:
      - db

  # MySQL Database Service
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd_2024
      MYSQL_DATABASE: fasms_dev
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d

  # phpMyAdmin Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: P@ssw0rd_2024
    depends_on:
      - db

volumes:
  db_data:
